require("aziznal.remap")
require("aziznal.set")
require("aziznal.lazy")
require("aziznal.autocmds")
require("aziznal.custom-plugins.tsc-quickfix")
require("aziznal.custom-plugins.color-format-converter")
require("aziznal.custom-plugins.persist-qf")
